### ISSUE TITLE
Too many error : We have HAR files and need to rebuild the three

### ISSUE THREAD

**Issue by FafnerKeyZee** [Lookyloo/monitoring#27]
Hello,

Some URLs cause the following message many times a day:
"We have HAR files and need to recycle the three."
Is there a way to fix it ?

BR,

**Comment by Rafiot** [comment]
It occurs when har2tree didn't manage to create the pickle, or that the pickle is broken and needs to be rebuilt. Normally, it is something that solves itself as the tree is rebuild or shown. That is **unless** we're not able to build the tree because the HAR is broken, creating too many recursive calls, things like that.

Can you share captures in this state? (in private, I assume)

**Comment by FafnerKeyZee** [comment]
I will try to catch them when it occurs , but when I go to the capture on lookyloo there is no error :/
